"""empty message

Revision ID: e7149effbb1f
Revises: 1cb8ecec7946
Create Date: 2023-09-01 12:40:01.450015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7149effbb1f'
down_revision = '1cb8ecec7946'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.drop_column('rotation_period')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rotation_period', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
